name: GitHub Pages deploy

on: [push]

jobs:
  update-pages-repo:
    env:
      BRANCH: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2
        with:
          # Pull submodules
          submodules: 'recursive'

      # Setup node environment
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/

      # Prepare, build and publish project
      - name: Install dependencies
        run: yarn

      - name: Build output files
        run: yarn build

      - name: Copy dist files to example page
        run: |
          cp -r dist/ example/dist
          cp example/example-dev.html example/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main
          folder: example
          repository-name: illiiiillllilii/illiiiillllilii.github.io
          target-folder: ${{ env.BRANCH }}
          token: ${{ secrets.TALY_GH_TOKEN }}
          git-config-name: github-actions
          git-config-email: action@github.com

      - uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          # todo get deploy status from step above
          status: "success"

          # todo compose deploy url
          url: https://illiiiillllilii.github.io/${{ env.BRANCH }}/index.html
          description: "Successfully deployed to pages"
          name: "Test page deployed!"
