name: GitHub Pages deploy

on: [push]

jobs:
  update-pages-repo:
    env:
      BRANCH: ${{ github.ref }}
      FOLDER_TO_BE_DEPLOYED: export
      PAGES_REPO: illiiiillllilii/illiiiillllilii.github.io
      PAGES_URL: https://illiiiillllilii.github.io/

    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2
        with:
          # Pull submodules
          submodules: 'recursive'

      # Setup node environment
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/

      # Prepare, build and publish project
      - name: Install dependencies
        run: yarn

      - name: Build output files
        run: yarn build

      - name: Compose export directory
        run: |
          mkdir export
          mkdir export/dist
          cp dist/editor.js export/dist/editor.js
          cp example/example.html export/example.html
          cp -r example/assets export/assets

      # GitHub Pages Deploy Action
      # https://github.com/JamesIves/github-pages-deploy-action
      - name: Deploy 🚀
        id: deploy_action
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          # GH Pages repo target branch name and folder
          branch: main
          target-folder: ${{ env.BRANCH }}
          repository-name: ${{ env.PAGES_REPO }}

          # Folder to be deployed
          folder: ${{ env.FOLDER_TO_BE_DEPLOYED }}

          # Access and author params
          token: ${{ secrets.TALY_GH_TOKEN }}
          git-config-name: github-actions
          git-config-email: action@github.com

      # Add deployment commit status
      # https://github.com/ouzi-dev/commit-status-updater
      - uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          # todo set status from ${{ steps.deploy_action.outputs.deployment_status }}
          status: success
          url: ${{ env.PAGES_URL }}${{ env.BRANCH }}/example.html

          # todo compose message and name depending on status
          description: "Successfully deployed to GH Pages"
          name: "Preview is ready!"
